# Exported from Render on 2025-03-14T10:52:38Z
services:
- type: web
  name: cahcet-college-backend
  runtime: node
  repo: https://github.com/Asjad-Zaki/cahcet-college
  plan: free
  envVars:
  - key: JWT_SECRET
    sync: false
  - key: MYSQL_PASSWORD
    sync: false
  - key: MYSQL_USER
    sync: false
  - key: MYSQL_DATABASE
    sync: false
  - key: MYSQL_PORT
    sync: false
  - key: MYSQL_HOST
    sync: false
  region: oregon
  buildCommand: npm install && cd server && npm install
  startCommand: npm run start
version: "1"

services:
  - type: web
    name: cahcetcollege-frontend
    env: static
    nodeVersion: 18.x
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://cahcetcollege-backend.onrender.com
      - key: GENERATE_SOURCEMAP
        value: false
      - key: SKIP_PREFLIGHT_CHECK
        value: true
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
